<a href="https://colab.research.google.com/github/khonshu1102/Big-Data-Analytics/blob/main/Ass2_31stJan_202301005.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question1
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
arr1 = arr[::-1]
print(arr1)


[5 4 6 3 2 1]


In [ ]:
#Question2
import numpy as np
arr1 = np.array([[7,2,1], [3,4]])
arr2 = np.array([[5,2,1], [3,4]])
if (arr1.all() == arr2.all()):
  print("SAME")
else:
  print("NOT SAME")



SAME


<ipython-input-15-101f9680d292>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1 = np.array([[7,2,1], [3,4]])
<ipython-input-15-101f9680d292>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[5,2,1], [3,4]])


In [ ]:
#Question3 1st Part
import numpy as np

x = np.array([1,2,3,4,5,1,2,1,1,1])

counts = np.bincount(x)  # Count occurrences of each element
most_frequent_value = counts.argmax()  # Find the index of the maximum count
indices = np.where(x == most_frequent_value)[0] # Find all indices of the most frequent value

print(f"Most frequent value: {most_frequent_value}")
print(f"Indices: {indices}")

# Question3 2nd Part
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

counts = np.bincount(y)
most_frequent_value = counts.argmax()
indices = np.where(y == most_frequent_value)[0]

print(f"Most frequent value: {most_frequent_value}")
print(f"Indices: {indices}")

Most frequent value: 1
Indices: [0 5 7 8 9]
Most frequent value: 1
Indices: [0 1 2]


In [ ]:
#Question4
import numpy as np

x = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(x)

sum_matrix = np.sum(x)
print("\n the sum of matrix is", sum_matrix)

sum_row = x.sum(axis = 1)
print("\n the sum of all rows are:", sum_row)

sum_col = x.sum(axis = 0)
print("\n the sum of all columns are:", sum_col)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

 the sum of matrix is 45

 the sum of all rows are: [[14]
 [16]
 [15]]

 the sum of all columns are: [[20  9 16]]
